version: "3.7"

services:
  ubuntu:
    image: "chaitanyatholada/sample-flask-app:ubuntu"
    container_name: "flask-app-ubuntu"
    ports:
      - "6000:5000"

  python:
    image: "chaitanyatholada/sample-flask-app:python"
    container_name: "flask-app-python"
    ports:
      - "7000:5000"

  multi-stage:
    image: "chaitanyatholada/sample-flask-app:multistage"
    container_name: "flask-app-multistage"
    ports:
      - "8000:5000"